name = "MetopDatasets"
uuid = "0c26954c-4046-4b98-a13c-f9377ca4b9b7"
version = "0.2.1"
authors = ["lupemba <simon.koklupemba@eumetsat.int> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"

[compat]
Aqua = "0.8.9"
CSV = "0.10"
CommonDataModel = "0.4"
Compat = "4.10"
Dates = "1"
DiskArrays = "0.3, 0.4"
LazyArtifacts = "1"
NCDatasets = "0.14"
OrderedCollections = "1"
PrecompileTools = "1"
RelocatableFolders = "1"
SafeTestsets = "0.1"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "NCDatasets", "SafeTestsets", "Test"]
